export const ROUTE_PATH = {
    HOME: '/',
    POST_CREATE: '/posts/create',
    POST_DETAIL: '/posts/:postId',
    POST_EDIT: '/posts/edit/:postId',
    SEARCH: '/search',
    FRIENDS: '/friends',
    BOOKMARKS: '/bookmarks',
    LIKES: '/likes',
    PROFILE: '/profile',
    PROFILE_MY_POST: 'post',
    PROFILE_MY_FRIEND: 'friend',
    PROFILE_ACTIVITY: 'activity',
    PROFILE_ACTIVITY_LIKES: 'likes',
    PROFILE_ACTIVITY_REPLIES: 'replies',
    NOTI: '/notifications',
    LOGIN: '/user/login',
    SIGNUP: '/user/signup',
    NOT_FOUND: '*',
} as const;
